### ISSUE TITLE
[zh-TW] 弃用一些旧字

### ISSUE THREAD

**Issue by m13253** [The-Orizon/utf8everywhere#12]
根据 MS Term：platform -> 平台
现在用的是“平臺”

**Comment by zerng07** [comment]
沒理由一定要遵照 MS Term 啊。
臺灣教育部規範正規場合都要寫「臺」不是「台」（任何官方考試上寫台都屬錯字）。

**Comment by zerng07** [comment]
MS 的東西不是很考究的，並非標準，只是多少可以拿來給翻譯者「參考」。

**Comment by zerng07** [comment]
個人真心認為這 issue 可以關了。

**Comment by m13253** [comment]
> 臺灣教育部規範正規場合都要寫「臺」不是「台」（任何官方考試上寫台都屬錯字）。

OK。按权威说法。
