### ISSUE TITLE
link of "For example, this is how Twitter counts characters." is invaild

### ISSUE THREAD

**Issue by wutiantong** [The-Orizon/utf8everywhere#15]
https://dev.twitter.com/docs/counting-characters is out-of-date
now, it's https://developer.twitter.com/en/docs/basics/counting-characters

**Comment by m13253** [comment]
Thank you for your report!

The Chinese translation is not updated for a while.
We need to gather people together again to update the translation.

In the mean while, you may help us do the translation by sending Pull Requests.

**Comment by wutiantong** [comment]
> Thank you for your report!
> 
> The Chinese translation is not updated for a while.
> We need to gather people together again to update the translation.
> 
> In the mean while, you may help us do the translation by sending Pull Requests.

Nice, I will
